DISABLE_UNTRACKED_FILES_DIRTY="true"
export TERM="xterm-256color"
source $(brew --prefix)/share/antigen/antigen.zsh

antigen use oh-my-zsh

setup_plugins() {
    antigen bundle git
    antigen bundle marked2
    antigen bundle mgryszko/jvm
    antigen bundle psprint/zsh-navigation-tools
    antigen bundle command-not-found
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen bundle osx
    antigen bundle Tarrasch/zsh-colors
    antigen bundle KyleChamberlin/zsh_maven_plugin
    antigen bundle docker
    antigen bundle golang
    antigen bundle gradle
    antigen bundle node
    antigen bundle npm
    antigen bundle nvm
    antigen bundle brew
    antigen bundle brew cask
}

setup_theme() {
    DEFAULT_USER=$USER
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
    POWERLEVEL9K_NODE_VERSION_FOREGROUND='black'
    POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context dir vcs)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv background_jobs)
    POWERLEVEL9K_STATUS_VERBOSE=true
    POWERLEVEL9K_SHOW_CHANGESET=true
    POWERLEVEL9K_CHANGESET_HASH_LENGTH=7

    POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
    POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
    POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k

    antigen theme bhilburn/powerlevel9k powerlevel9k
}

setup_plugins && antigen apply


export PATH=/usr/local/bin:$PATH

# added by travis gem
[ -f /Users/faizhasim/.travis/travis.sh ] && source /Users/faizhasim/.travis/travis.sh

# Hyperterm Compatability (see https://github.com/zeit/hyperterm/issues/360)
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export GOPATH="${HOME}/dev/go"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

test -d "${GOPATH}" || mkdir "${GOPATH}"
test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"

export PATH="/usr/local/sbin:/usr/local/mysql/bin:$HOME/.yarn/bin:$PATH"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/faizhasim/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/faizhasim/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/faizhasim/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/faizhasim/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh

eval "$(direnv hook zsh)"

# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/faizhasim/.config/yarn/global/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/faizhasim/.config/yarn/global/node_modules/tabtab/.completions/slss.zshexport


# #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="/Users/faizhasim/.sdkman"
# [[ -s "/Users/faizhasim/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/faizhasim/.sdkman/bin/sdkman-init.sh"

eval "$(starship init zsh)"
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export SSH_AUTH_SOCK=$HOME/.sekey/ssh-agent.ssh
export HOMEBREW_GITHUB_API_TOKEN="xxxx"

if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"